# Generated by Django 3.2.9 on 2021-11-14 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrioritySubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folderId', models.CharField(max_length=20)),
                ('folderPermalink', models.URLField(max_length=100, null=True)),
                ('title', models.CharField(max_length=200)),
                ('startDate', models.DateTimeField(null=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
                ('linksProvided', models.CharField(max_length=1000, null=True)),
                ('workImpact', models.CharField(max_length=20000, null=True)),
                ('statement', models.CharField(max_length=20000, null=True)),
                ('submitter', models.CharField(max_length=100, null=True)),
                ('possibleSolutions', models.CharField(max_length=20000, null=True)),
                ('solutionRequirements', models.CharField(max_length=2000, null=True)),
                ('solutionDeveloper', models.CharField(max_length=100, null=True)),
                ('inputContributor', models.CharField(max_length=100, null=True)),
                ('agreer', models.CharField(max_length=100, null=True)),
                ('decider', models.CharField(max_length=100, null=True)),
                ('implementor', models.CharField(max_length=100, null=True)),
                ('acceptor', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
