# Generated by Django 3.2.9 on 2021-11-26 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211126_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prioritysubmission',
            name='startDate',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
